// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystem = "system"

// System mapped from table <system>
type System struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string         `gorm:"column:name;not null;comment:系统名称" json:"name"`               // 系统名称
	Description string         `gorm:"column:description;not null;comment:系统描述" json:"description"` // 系统描述
	Enable      bool           `gorm:"column:enable;not null;default:1;comment:是否启用" json:"enable"` // 是否启用
	CreatedAt   time.Time      `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`   // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`            // 删除时间
}

// TableName System's table name
func (*System) TableName() string {
	return TableNameSystem
}
